# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'LQBaseProject' do
  pod 'AFNetworking’, '~> 3.0'
  pod 'SDWebImage', '~> 3.8.1'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'ChameleonFramework'
  pod 'iCarousel', '~> 1.8.2'
  pod 'DateTools'
end

